[package]
name = "integration-tests"
publish = false
description = "Integration tests for composefs-rs (not published)"

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[[bin]]
name = "cfsctl-integration-tests"
path = "src/main.rs"

[[bin]]
name = "test-cleanup"
path = "src/cleanup.rs"

[dependencies]
anyhow = "1"
cap-std-ext = "4.0"
composefs-oci = { path = "../composefs-oci", version = "0.3.0", features = ["containers-storage"] }
hex = "0.4"
libtest-mimic = "0.8"
linkme = "0.3"
ocidir = "0.6"
paste = "1"
rustix = { version = "1", features = ["fs", "process"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tar = "0.4"
tempfile = "3"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
xshell = "0.2"

[lints]
workspace = true
